<?php
/**
 * Created by PhpStorm.
 * User: lihaijiang
 * Date: 2018/9/17
 * Time: 下午5:35
 */
namespace app\common\controller;

use think\Controller;

class HomeBase extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

}